import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Poppins } from 'next/font/google';
import { Coustard } from "next/font/google";
import Head from 'next/head';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const poppins = Poppins({ subsets: ['latin'],weight: ["100", "300", "400", "700", "900"], variable: '--font-poppins' });

const coustard = Coustard({ subsets: ['latin'],weight: ["400"], variable: '--font-poppins' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-neutral-900`}
        style={{ backgroundColor: "white" }}
      
      >
        

        <Navbar />
        {children}
        <div className="bg-neutral-800">
          <p className="text-neutral-400 text-sm text-center py-2">ডেভেলপড বাই - শিহাব আহমেদ</p>
        </div>
      </body>
    </html>
  );
}
